easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Comment
        - App\Entity\Category
        - App\Entity\User
        - App\Entity\Traobject
        - App\Entity\State
        - App\Entity\County
        - App\Entity\Message

